---
# K8S / Harness
envName: <+env.name>
appName: <+service.name>
artifactImage: <+artifact.image>  # from Harness Service Primary Artifact
containerPort: 80
servicePort: 80
namespace: <+service.name>-<+env.name>
ingressDomainName: <+serviceVariables.ingressDomainName>

# Application
## General
viteApiUrl: <+serviceVariables.viteApiUrl>
viteFrontendUrl: <+serviceVariables.viteFrontendUrl>
viteHelloSignClientId: <+serviceVariables.viteHelloSignClientId>
