---
apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.namespace}}
  name: {{.Values.appName}}-{{.Values.envName}}-svc
  labels:
    app: {{.Values.appName}}-{{.Values.envName}}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{.Values.servicePort}}
      targetPort: {{.Values.containerPort}}
  selector:
    app: {{.Values.appName}}-{{.Values.envName}}